-- Jingrui Feng (jf4446) - database systems project part 2 - load product records into database

-- ============================================
-- LOAD 1: Product (15 rows)
-- ============================================
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Term Life','S100','Standard','ADB','P1001','RB-NE','Level term life coverage','Death benefit paid to beneficiary',620.00,1);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Term Life','S100','Preferred','WOP','P1002','RB-NE','Level term life coverage','Death benefit paid to beneficiary',845.50,2);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Term Life','S200','Standard',NULL,'P1003','RB-SE','Level term life coverage','Death benefit paid to beneficiary',1120.00,3);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Term Life','S200','Select','CHILD','P1004','RB-SE','Level term life coverage','Death benefit paid to beneficiary',1480.75,4);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Term Life','S300','Standard',NULL,'P1005','RB-MW','Level term life coverage','Death benefit paid to beneficiary',1935.00,5);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Whole Life','S100','Standard','GIO','P2001','RB-NE','Permanent life with cash value','Cash value accumulation',2410.00,6);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Whole Life','S100','Select',NULL,'P2002','RB-MW','Permanent life with cash value','Cash value accumulation',2875.25,7);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Whole Life','S200','Preferred','ADB','P2003','RB-SE','Permanent life with cash value','Cash value accumulation',3320.00,8);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Whole Life','S200','Select','WOP','P2004','RB-WE','Permanent life with cash value','Level premium guarantee',3790.50,9);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Whole Life','S300','Standard',NULL,'P2005','RB-WE','Permanent life with cash value','Level premium guarantee',4260.00,10);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Universal Life','S100','Standard',NULL,'P3001','RB-NE','Flexible premium life coverage','Cash value accumulation',4715.00,11);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Universal Life','S100','Preferred','CHILD','P3002','RB-MW','Flexible premium life coverage','Cash value accumulation',5180.25,12);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Universal Life','S200','Standard','GIO','P3003','RB-SE','Flexible premium life coverage','Level premium guarantee',5540.00,13);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Universal Life','S200','Select',NULL,'P3004','RB-WE','Flexible premium life coverage','Level premium guarantee',5825.75,14);
INSERT INTO Product (LineOfBusiness,SeriesName,PlanName,RiderName,PlanCode,RatebookLocationCode,Description,Benefit,AnnualizedPremium,ProductID) VALUES ('Universal Life','S300','Preferred','ADB','P3005','RB-WE','Flexible premium life coverage','Death benefit paid to beneficiary',5990.00,15);
