-- Jingrui Feng (jf4446) - database systems project part 2 - define portal-ready life insurance relational schema

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-07-21 16:17:07 EDT
--   site:      SQL Server 2012
--   type:      SQL Server 2012

CREATE TABLE Account 
    (
     AccountName VARCHAR (60) NOT NULL , 
     AccountName2 VARCHAR (60) NOT NULL , 
     LocationAddress1 VARCHAR (60) NOT NULL , 
     LocationAddress2 VARCHAR (60) NOT NULL , 
     LocationCity VARCHAR (40) NOT NULL , 
     LocationState VARCHAR (2) NOT NULL , 
     LocationZip VARCHAR (10) NOT NULL , 
     CompanyCode VARCHAR (10) NOT NULL , 
     TaxIDNumber VARCHAR (15) , 
     NumberOfEmployees INTEGER , 
     ActivityStatus VARCHAR (10) , 
     GroupNumber VARCHAR (20) , 
     LegacyFlexID VARCHAR (20) , 
     PlanYearStartDate DATE , 
     PlanYearEndDate DATE , 
     StandardIndustryCode VARCHAR (10) , 
     HSAFlag CHAR (1) , 
     HRAFlag CHAR (1) , 
     AnnualizedPremium NUMERIC (12,2) , 
     AccountID INTEGER NOT NULL 
    );

ALTER TABLE Account ADD CONSTRAINT Account_PK PRIMARY KEY CLUSTERED (AccountID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE Account ADD CONSTRAINT Account_AccountName_AccountName2_LocationAddress1_LocationAddress2_LocationCity_LocationState_LocationZip_CompanyCode_UN UNIQUE NONCLUSTERED (AccountName, AccountName2, LocationAddress1, LocationAddress2, LocationCity, LocationState, LocationZip, CompanyCode);

CREATE TABLE AccountAlias 
    (
     AccountName VARCHAR (60) NOT NULL , 
     AccountName2 VARCHAR (60) NOT NULL , 
     LocationAddress1 VARCHAR (60) NOT NULL , 
     LocationAddress2 VARCHAR (60) NOT NULL , 
     LocationCity VARCHAR (40) NOT NULL , 
     LocationState VARCHAR (2) NOT NULL , 
     LocationZip VARCHAR (10) NOT NULL , 
     CompanyCode VARCHAR (10) NOT NULL , 
     AliasSource VARCHAR (20) NOT NULL , 
     AliasID VARCHAR (20) NOT NULL , 
     AliasName VARCHAR (60) , 
     AliasAddress1 VARCHAR (60) , 
     AliasAddress2 VARCHAR (60) , 
     AliasCity VARCHAR (40) , 
     AliasState VARCHAR (2) , 
     AliasZip VARCHAR (10) , 
     AliasPhone VARCHAR (15) , 
     AliasEMailAddress VARCHAR (60) , 
     AliasFax VARCHAR (15) , 
     Account_AccountID INTEGER NOT NULL , 
     AccountAliasID INTEGER NOT NULL 
    );

ALTER TABLE AccountAlias ADD CONSTRAINT AccountAlias_PK PRIMARY KEY CLUSTERED (AccountAliasID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE AccountAlias ADD CONSTRAINT AccountAlias_AliasSource_AliasID_UN UNIQUE NONCLUSTERED (AliasSource, AliasID);

CREATE TABLE AccountMember 
    (
     AccountName VARCHAR (60) NOT NULL , 
     AccountName2 VARCHAR (60) NOT NULL , 
     LocationAddress1 VARCHAR (60) NOT NULL , 
     LocationAddress2 VARCHAR (60) NOT NULL , 
     LocationCity VARCHAR (40) NOT NULL , 
     LocationState VARCHAR (2) NOT NULL , 
     LocationZip VARCHAR (10) NOT NULL , 
     CompanyCode VARCHAR (10) NOT NULL , 
     CustLastName VARCHAR (40) NOT NULL , 
     CustFirstName VARCHAR (40) NOT NULL , 
     CustMiddleInitial VARCHAR (2) NOT NULL , 
     CustSuffix VARCHAR (10) NOT NULL , 
     CustDOB DATE NOT NULL , 
     StartDate DATE NOT NULL , 
     EndDate DATE , 
     FSAContributionAmount NUMERIC (12,2) , 
     CustBAcctDepartmentName VARCHAR (40) , 
     Customer_CustomerID INTEGER NOT NULL , 
     Account_AccountID INTEGER NOT NULL , 
     AccountMemberID INTEGER NOT NULL 
    );

ALTER TABLE AccountMember ADD CONSTRAINT AccountMember_PK PRIMARY KEY CLUSTERED (AccountMemberID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Administrator 
    (
     AdminID VARCHAR (15) NOT NULL , 
     AdminLastName VARCHAR (40) , 
     AdminFirstName VARCHAR (40) , 
     AdminMiddleInitial VARCHAR (2) , 
     AdminSuffix VARCHAR (10) , 
     AdminAddress1 VARCHAR (60) , 
     AdminAddress2 VARCHAR (60) , 
     AdminCity VARCHAR (40) , 
     AdminState VARCHAR (2) , 
     AdminZip VARCHAR (10) , 
     Phone VARCHAR (15) , 
     FaxNumber VARCHAR (15) , 
     Gender VARCHAR (1) , 
     EMailAddress VARCHAR (60) 
    );

ALTER TABLE Administrator ADD CONSTRAINT Administrator_PK PRIMARY KEY CLUSTERED (AdminID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Associate 
    (
     AssocLastName VARCHAR (40) NOT NULL , 
     AssocFirstName VARCHAR (40) NOT NULL , 
     AssocMiddleInitial VARCHAR (2) NOT NULL , 
     AssocSuffix VARCHAR (10) NOT NULL , 
     AssocDOB DATE NOT NULL , 
     TenureDate DATE , 
     ConsolAssocID VARCHAR (15) , 
     CorpEMailAddress VARCHAR (60) , 
     AssocPhone VARCHAR (15) , 
     AssocAddress1 VARCHAR (60) , 
     AssocAddress2 VARCHAR (60) , 
     AssocCity VARCHAR (40) , 
     AssocState VARCHAR (2) , 
     AssocZip VARCHAR (10) , 
     DBAName VARCHAR (60) , 
     AssocLastName1 VARCHAR (40) , 
     AssocFirstName1 VARCHAR (40) , 
     AssocMiddleInitial1 VARCHAR (2) , 
     AssocSuffix1 VARCHAR (10) , 
     AssocDOB1 DATE , 
     AssociateID INTEGER NOT NULL , 
     Associate_AssociateID INTEGER NOT NULL 
    );

ALTER TABLE Associate ADD CONSTRAINT Associate_PK PRIMARY KEY CLUSTERED (AssociateID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE Associate ADD CONSTRAINT Associate_AssocLastName_AssocFirstName_AssocMiddleInitial_AssocSuffix_AssocDOB_UN UNIQUE NONCLUSTERED (AssocLastName, AssocFirstName, AssocMiddleInitial, AssocSuffix, AssocDOB);

CREATE TABLE BillingAccount 
    (
     BAcctName VARCHAR (60) NOT NULL , 
     BAcctName2 VARCHAR (60) NOT NULL , 
     BillingAddress1 VARCHAR (60) NOT NULL , 
     BillingAddress2 VARCHAR (60) NOT NULL , 
     BillingCity VARCHAR (40) NOT NULL , 
     BillingState VARCHAR (2) NOT NULL , 
     BillingZip VARCHAR (10) NOT NULL , 
     GroupNumber VARCHAR (20) , 
     TaxIDNumber VARCHAR (15) , 
     GeoCode VARCHAR (10) , 
     OnlineBillingFlag CHAR (1) , 
     ActivityStatus VARCHAR (10) , 
     BillingPhone VARCHAR (15) , 
     BillingAccountID INTEGER NOT NULL 
    );

ALTER TABLE BillingAccount ADD CONSTRAINT BillingAccount_PK PRIMARY KEY CLUSTERED (BillingAccountID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE BillingAccount ADD CONSTRAINT BillingAccount_BAcctName_BAcctName2_BillingAddress1_BillingAddress2_BillingCity_BillingState_BillingZip_UN UNIQUE NONCLUSTERED (BAcctName, BAcctName2, BillingAddress1, BillingAddress2, BillingCity, BillingState, BillingZip);

CREATE TABLE Claim 
    (
     ClaimNumber VARCHAR (20) NOT NULL , 
     ClaimDate DATE , 
     SettlementDate DATE , 
     WellnessEligibilityDate DATE , 
     ClaimID INTEGER NOT NULL , 
     Contract_ContractID INTEGER 
    );

ALTER TABLE Claim ADD CONSTRAINT Claim_PK PRIMARY KEY CLUSTERED (ClaimID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE Claim ADD CONSTRAINT Claim_ClaimNumber_UN UNIQUE NONCLUSTERED (ClaimNumber);

CREATE TABLE Contest 
    (
     ContestName VARCHAR (40) NOT NULL , 
     StartDate DATE NOT NULL , 
     Prize VARCHAR (60) , 
     PrizeAmount NUMERIC (12,2) , 
     EndDate DATE , 
     Criteria VARCHAR (255) , 
     Threshold NUMERIC (12,2) , 
     ContestID INTEGER NOT NULL 
    );

ALTER TABLE Contest ADD CONSTRAINT Contest_PK PRIMARY KEY CLUSTERED (ContestID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE Contest ADD CONSTRAINT Contest_ContestName_StartDate_UN UNIQUE NONCLUSTERED (ContestName, StartDate);

CREATE TABLE Contract 
    (
     ContractNumber VARCHAR (20) NOT NULL , 
     LineOfBusiness VARCHAR (20) , 
     SeriesName VARCHAR (10) , 
     PlanName VARCHAR (10) , 
     ActivityStatus VARCHAR (10) , 
     CoverageType VARCHAR (20) , 
     BillingMethod VARCHAR (20) , 
     ModalPremium NUMERIC (12,2) , 
     InForceFlag CHAR (1) , 
     PayUpDate DATE , 
     Duration INTEGER , 
     Language VARCHAR (20) , 
     CreditCardNo VARCHAR (20) , 
     CardType VARCHAR (10) , 
     BankingTransitNumber VARCHAR (9) , 
     BankingAccountType VARCHAR (10) , 
     BankingAccountNumber VARCHAR (20) , 
     ContractID INTEGER NOT NULL , 
     Product_ProductID INTEGER 
    );

ALTER TABLE Contract ADD CONSTRAINT Contract_PK PRIMARY KEY CLUSTERED (ContractID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE Contract ADD CONSTRAINT Contract_ContractNumber_UN UNIQUE NONCLUSTERED (ContractNumber);

CREATE TABLE ContractBenefit 
    (
     ContractNumber VARCHAR (20) NOT NULL , 
     LineOfBusiness VARCHAR (20) NOT NULL , 
     SeriesName VARCHAR (10) NOT NULL , 
     PlanName VARCHAR (10) NOT NULL , 
     RiderName VARCHAR (10) NOT NULL , 
     PolicyCountContribution NUMERIC (12,2) , 
     Contract_ContractID INTEGER NOT NULL , 
     ContractBenefitID INTEGER NOT NULL 
    );

ALTER TABLE ContractBenefit ADD CONSTRAINT ContractBenefit_PK PRIMARY KEY CLUSTERED (ContractBenefitID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE ContractBenefit ADD CONSTRAINT ContractBenefit_ContractNumber_LineOfBusiness_SeriesName_PlanName_RiderName_UN UNIQUE NONCLUSTERED (ContractNumber, LineOfBusiness, SeriesName, PlanName, RiderName);

CREATE TABLE ContractParty 
    (
     ContractNumber VARCHAR (20) NOT NULL , 
     CustLastName VARCHAR (40) NOT NULL , 
     CustFirstName VARCHAR (40) NOT NULL , 
     CustMiddleInitial VARCHAR (2) NOT NULL , 
     CustSuffix VARCHAR (10) NOT NULL , 
     CustDOB DATE NOT NULL , 
     Role VARCHAR (20) NOT NULL , 
     BenefitReference VARCHAR (20) , 
     StartDate DATE , 
     EndDate DATE , 
     Customer_CustomerID INTEGER , 
     Contract_ContractID INTEGER , 
     ContractBenefit_ContractBenefitID INTEGER , 
     ContractPartyID INTEGER NOT NULL 
    );

ALTER TABLE ContractParty ADD CONSTRAINT ContractParty_PK PRIMARY KEY CLUSTERED (ContractPartyID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE ContractPremium 
    (
     ContractNumber VARCHAR (20) NOT NULL , 
     LineOfBusiness VARCHAR (20) NOT NULL , 
     SeriesName VARCHAR (10) NOT NULL , 
     PlanName VARCHAR (10) NOT NULL , 
     RiderName VARCHAR (10) NOT NULL , 
     PremiumCode VARCHAR (10) NOT NULL , 
     AnnualizedPremium NUMERIC (12,2) , 
     ProcessDate DATE , 
     AppSignDate DATE , 
     ContractBenefit_ContractBenefitID INTEGER NOT NULL , 
     ContractPremiumID INTEGER NOT NULL 
    );

ALTER TABLE ContractPremium ADD CONSTRAINT ContractPremium_PK PRIMARY KEY CLUSTERED (ContractPremiumID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE ContractPremium ADD CONSTRAINT ContractPremium_ContractNumber_LineOfBusiness_SeriesName_PlanName_RiderName_PremiumCode_UN UNIQUE NONCLUSTERED (ContractNumber, LineOfBusiness, SeriesName, PlanName, RiderName, PremiumCode);

CREATE TABLE Customer 
    (
     CustLastName VARCHAR (40) NOT NULL , 
     CustFirstName VARCHAR (40) NOT NULL , 
     CustMiddleInitial VARCHAR (2) NOT NULL , 
     CustSuffix VARCHAR (10) NOT NULL , 
     CustDOB DATE NOT NULL , 
     CustSalutation VARCHAR (10) , 
     CusteMailAddress VARCHAR (60) , 
     Gender VARCHAR (1) , 
     SSN_TIN VARCHAR (11) , 
     SSNType VARCHAR (10) , 
     CustomerLegacyID VARCHAR (20) , 
     WithholdingCode VARCHAR (10) , 
     PreferredLanguage VARCHAR (20) , 
     StartDate DATE , 
     EndDate DATE , 
     CustomerID INTEGER NOT NULL 
    );

ALTER TABLE Customer ADD CONSTRAINT Customer_PK PRIMARY KEY CLUSTERED (CustomerID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE Customer ADD CONSTRAINT Customer_CustLastName_CustFirstName_CustMiddleInitial_CustSuffix_CustDOB_UN UNIQUE NONCLUSTERED (CustLastName, CustFirstName, CustMiddleInitial, CustSuffix, CustDOB);

CREATE TABLE Invoice 
    (
     InvoiceNumber VARCHAR (20) NOT NULL , 
     PaidDate DATE , 
     DueDate DATE , 
     RunDate DATE , 
     PremiumSubTotal NUMERIC (12,2) , 
     PaymentMethod VARCHAR (10) , 
     PaymentDate DATE , 
     RemittanceFreq VARCHAR (10) , 
     BillingAccount_BillingAccountID INTEGER NOT NULL , 
     InvoiceID INTEGER NOT NULL 
    );

ALTER TABLE Invoice ADD CONSTRAINT Invoice_PK PRIMARY KEY CLUSTERED (InvoiceID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE Invoice ADD CONSTRAINT Invoice_InvoiceNumber_UN UNIQUE NONCLUSTERED (InvoiceNumber);

CREATE TABLE ManagerContract 
    (
     SitCode VARCHAR (10) NOT NULL , 
     CompanyCode VARCHAR (10) NOT NULL , 
     WritingNumber VARCHAR (15) NOT NULL , 
     Level VARCHAR (10) NOT NULL , 
     IssueDate DATE NOT NULL , 
     ContractType VARCHAR (20) , 
     CommissionCode VARCHAR (10) , 
     Role VARCHAR (20) , 
     ParentSitCode VARCHAR (10) , 
     StartDate DATE , 
     EndDate DATE , 
     AssocLastName VARCHAR (40) , 
     AssocFirstName VARCHAR (40) , 
     AssocMiddleInitial VARCHAR (2) , 
     AssocSuffix VARCHAR (10) , 
     AssocDOB DATE , 
     ManagerContractID INTEGER NOT NULL , 
     WritingNumber_WritingNumberID INTEGER NOT NULL , 
     ManagerContract_ManagerContractID INTEGER NOT NULL , 
     AssociateID INTEGER NOT NULL 
    );

ALTER TABLE ManagerContract ADD CONSTRAINT ManagerContract_PK PRIMARY KEY CLUSTERED (ManagerContractID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE ManagerContract ADD CONSTRAINT ManagerContract_SitCode_CompanyCode_WritingNumber_Level_IssueDate_UN UNIQUE NONCLUSTERED (SitCode, CompanyCode, WritingNumber, Level, IssueDate);

CREATE TABLE OrgUnit 
    (
     OrgUnitID VARCHAR (15) NOT NULL , 
     OrgLevel INTEGER , 
     Name VARCHAR (60) , 
     ParentOrgUnitID VARCHAR (15) , 
     StartDate DATE , 
     EndDate DATE , 
     StateCode VARCHAR (2) , 
     OrgUnit_OrgUnitID VARCHAR (15) NOT NULL 
    );

ALTER TABLE OrgUnit ADD CONSTRAINT OrgUnit_PK PRIMARY KEY CLUSTERED (OrgUnitID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Product 
    (
     LineOfBusiness VARCHAR (20) NOT NULL , 
     SeriesName VARCHAR (10) NOT NULL , 
     PlanName VARCHAR (10) NOT NULL , 
     RiderName VARCHAR (10) , 
     PlanCode VARCHAR (10) , 
     RatebookLocationCode VARCHAR (10) , 
     Description VARCHAR (255) , 
     Benefit VARCHAR (60) , 
     AnnualizedPremium NUMERIC (12,2) , 
     ProductID INTEGER NOT NULL 
    );

ALTER TABLE Product ADD CONSTRAINT Product_PK PRIMARY KEY CLUSTERED (ProductID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE Product ADD CONSTRAINT Product_LineOfBusiness_SeriesName_PlanName_UN UNIQUE NONCLUSTERED (LineOfBusiness, SeriesName, PlanName);

CREATE TABLE Relation_24 
    (
     Claim_ClaimID INTEGER NOT NULL , 
     Customer_CustomerID INTEGER NOT NULL 
    );

ALTER TABLE Relation_24 ADD CONSTRAINT Relation_24_PK PRIMARY KEY CLUSTERED (Claim_ClaimID, Customer_CustomerID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_26 
    (
     Claim_ClaimID INTEGER NOT NULL , 
     ContractBenefit_ContractBenefitID INTEGER NOT NULL 
    );

ALTER TABLE Relation_26 ADD CONSTRAINT Relation_26_PK PRIMARY KEY CLUSTERED (Claim_ClaimID, ContractBenefit_ContractBenefitID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_27 
    (
     Account_AccountID INTEGER NOT NULL , 
     ManagerContract_ManagerContractID INTEGER NOT NULL 
    );

ALTER TABLE Relation_27 ADD CONSTRAINT Relation_27_PK PRIMARY KEY CLUSTERED (Account_AccountID, ManagerContract_ManagerContractID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_28 
    (
     ContractPremium_ContractPremiumID INTEGER NOT NULL , 
     ManagerContract_ManagerContractID INTEGER NOT NULL 
    );

ALTER TABLE Relation_28 ADD CONSTRAINT Relation_28_PK PRIMARY KEY CLUSTERED (ContractPremium_ContractPremiumID, ManagerContract_ManagerContractID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_29 
    (
     ContractPremium_ContractPremiumID INTEGER NOT NULL , 
     OrgUnit_OrgUnitID VARCHAR (15) NOT NULL 
    );

ALTER TABLE Relation_29 ADD CONSTRAINT Relation_29_PK PRIMARY KEY CLUSTERED (ContractPremium_ContractPremiumID, OrgUnit_OrgUnitID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_3 
    (
     Account_AccountID INTEGER NOT NULL , 
     BillingAccount_BillingAccountID INTEGER NOT NULL 
    );

ALTER TABLE Relation_3 ADD CONSTRAINT Relation_3_PK PRIMARY KEY CLUSTERED (Account_AccountID, BillingAccount_BillingAccountID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_30 
    (
     Associate_AssociateID INTEGER NOT NULL , 
     OrgUnit_OrgUnitID VARCHAR (15) NOT NULL 
    );

ALTER TABLE Relation_30 ADD CONSTRAINT Relation_30_PK PRIMARY KEY CLUSTERED (Associate_AssociateID, OrgUnit_OrgUnitID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_31 
    (
     Associate_AssociateID INTEGER NOT NULL , 
     Contest_ContestID INTEGER NOT NULL 
    );

ALTER TABLE Relation_31 ADD CONSTRAINT Relation_31_PK PRIMARY KEY CLUSTERED (Associate_AssociateID, Contest_ContestID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_32 
    (
     Customer_CustomerID INTEGER NOT NULL , 
     Associate_AssociateID INTEGER NOT NULL 
    );

ALTER TABLE Relation_32 ADD CONSTRAINT Relation_32_PK PRIMARY KEY CLUSTERED (Customer_CustomerID, Associate_AssociateID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_39 
    (
     Account_AccountID INTEGER NOT NULL , 
     Account_AccountID1 INTEGER NOT NULL 
    );

ALTER TABLE Relation_39 ADD CONSTRAINT Relation_39_PK PRIMARY KEY CLUSTERED (Account_AccountID, Account_AccountID1)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE Relation_5 
    (
     Account_AccountID INTEGER NOT NULL , 
     Administrator_AdminID VARCHAR (15) NOT NULL 
    );

ALTER TABLE Relation_5 ADD CONSTRAINT Relation_5_PK PRIMARY KEY CLUSTERED (Account_AccountID, Administrator_AdminID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE WritingNumber 
    (
     CompanyCode VARCHAR (10) NOT NULL , 
     WritingNumber VARCHAR (15) NOT NULL , 
     AssocLastName VARCHAR (40) , 
     AssocFirstName VARCHAR (40) , 
     AssocMiddleInitial VARCHAR (2) , 
     AssocSuffix VARCHAR (10) , 
     AssocDOB DATE , 
     IssueDate DATE , 
     Status VARCHAR (10) , 
     VestedFlag CHAR (1) , 
     TerminationDate DATE , 
     LicenseState VARCHAR (2) , 
     LicenseNumber VARCHAR (20) , 
     LineOfBusiness VARCHAR (20) , 
     AssociateID INTEGER NOT NULL , 
     WritingNumberID INTEGER NOT NULL , 
     Associate_AssociateID INTEGER NOT NULL 
    );

ALTER TABLE WritingNumber ADD CONSTRAINT WritingNumber_PK PRIMARY KEY CLUSTERED (WritingNumberID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
ALTER TABLE WritingNumber ADD CONSTRAINT WritingNumber_CompanyCode_WritingNumber_UN UNIQUE NONCLUSTERED (CompanyCode, WritingNumber);

ALTER TABLE AccountAlias 
    ADD CONSTRAINT AccountAlias_Account_FK FOREIGN KEY 
    ( 
     Account_AccountID
    ) 
    REFERENCES Account 
    ( 
     AccountID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE AccountMember 
    ADD CONSTRAINT AccountMember_Account_FK FOREIGN KEY 
    ( 
     Account_AccountID
    ) 
    REFERENCES Account 
    ( 
     AccountID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE AccountMember 
    ADD CONSTRAINT AccountMember_Customer_FK FOREIGN KEY 
    ( 
     Customer_CustomerID
    ) 
    REFERENCES Customer 
    ( 
     CustomerID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Associate 
    ADD CONSTRAINT Associate_Associate_FK FOREIGN KEY 
    ( 
     Associate_AssociateID
    ) 
    REFERENCES Associate 
    ( 
     AssociateID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Claim 
    ADD CONSTRAINT Claim_Contract_FK FOREIGN KEY 
    ( 
     Contract_ContractID
    ) 
    REFERENCES Contract 
    ( 
     ContractID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Contract 
    ADD CONSTRAINT Contract_Product_FK FOREIGN KEY 
    ( 
     Product_ProductID
    ) 
    REFERENCES Product 
    ( 
     ProductID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE ContractBenefit 
    ADD CONSTRAINT ContractBenefit_Contract_FK FOREIGN KEY 
    ( 
     Contract_ContractID
    ) 
    REFERENCES Contract 
    ( 
     ContractID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE ContractParty 
    ADD CONSTRAINT ContractParty_Contract_FK FOREIGN KEY 
    ( 
     Contract_ContractID
    ) 
    REFERENCES Contract 
    ( 
     ContractID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE ContractParty 
    ADD CONSTRAINT ContractParty_ContractBenefit_FK FOREIGN KEY 
    ( 
     ContractBenefit_ContractBenefitID
    ) 
    REFERENCES ContractBenefit 
    ( 
     ContractBenefitID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE ContractParty 
    ADD CONSTRAINT ContractParty_Customer_FK FOREIGN KEY 
    ( 
     Customer_CustomerID
    ) 
    REFERENCES Customer 
    ( 
     CustomerID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE ContractPremium 
    ADD CONSTRAINT ContractPremium_ContractBenefit_FK FOREIGN KEY 
    ( 
     ContractBenefit_ContractBenefitID
    ) 
    REFERENCES ContractBenefit 
    ( 
     ContractBenefitID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Invoice 
    ADD CONSTRAINT Invoice_BillingAccount_FK FOREIGN KEY 
    ( 
     BillingAccount_BillingAccountID
    ) 
    REFERENCES BillingAccount 
    ( 
     BillingAccountID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE ManagerContract 
    ADD CONSTRAINT ManagerContract_ManagerContract_FK FOREIGN KEY 
    ( 
     ManagerContract_ManagerContractID
    ) 
    REFERENCES ManagerContract 
    ( 
     ManagerContractID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE ManagerContract 
    ADD CONSTRAINT ManagerContract_WritingNumber_FK FOREIGN KEY 
    ( 
     WritingNumber_WritingNumberID
    ) 
    REFERENCES WritingNumber 
    ( 
     WritingNumberID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE OrgUnit 
    ADD CONSTRAINT OrgUnit_OrgUnit_FK FOREIGN KEY 
    ( 
     OrgUnit_OrgUnitID
    ) 
    REFERENCES OrgUnit 
    ( 
     OrgUnitID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_24 
    ADD CONSTRAINT Relation_24_Claim_FK FOREIGN KEY 
    ( 
     Claim_ClaimID
    ) 
    REFERENCES Claim 
    ( 
     ClaimID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_24 
    ADD CONSTRAINT Relation_24_Customer_FK FOREIGN KEY 
    ( 
     Customer_CustomerID
    ) 
    REFERENCES Customer 
    ( 
     CustomerID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_26 
    ADD CONSTRAINT Relation_26_Claim_FK FOREIGN KEY 
    ( 
     Claim_ClaimID
    ) 
    REFERENCES Claim 
    ( 
     ClaimID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_26 
    ADD CONSTRAINT Relation_26_ContractBenefit_FK FOREIGN KEY 
    ( 
     ContractBenefit_ContractBenefitID
    ) 
    REFERENCES ContractBenefit 
    ( 
     ContractBenefitID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_27 
    ADD CONSTRAINT Relation_27_Account_FK FOREIGN KEY 
    ( 
     Account_AccountID
    ) 
    REFERENCES Account 
    ( 
     AccountID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_27 
    ADD CONSTRAINT Relation_27_ManagerContract_FK FOREIGN KEY 
    ( 
     ManagerContract_ManagerContractID
    ) 
    REFERENCES ManagerContract 
    ( 
     ManagerContractID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_28 
    ADD CONSTRAINT Relation_28_ContractPremium_FK FOREIGN KEY 
    ( 
     ContractPremium_ContractPremiumID
    ) 
    REFERENCES ContractPremium 
    ( 
     ContractPremiumID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_28 
    ADD CONSTRAINT Relation_28_ManagerContract_FK FOREIGN KEY 
    ( 
     ManagerContract_ManagerContractID
    ) 
    REFERENCES ManagerContract 
    ( 
     ManagerContractID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_29 
    ADD CONSTRAINT Relation_29_ContractPremium_FK FOREIGN KEY 
    ( 
     ContractPremium_ContractPremiumID
    ) 
    REFERENCES ContractPremium 
    ( 
     ContractPremiumID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_29 
    ADD CONSTRAINT Relation_29_OrgUnit_FK FOREIGN KEY 
    ( 
     OrgUnit_OrgUnitID
    ) 
    REFERENCES OrgUnit 
    ( 
     OrgUnitID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_3 
    ADD CONSTRAINT Relation_3_Account_FK FOREIGN KEY 
    ( 
     Account_AccountID
    ) 
    REFERENCES Account 
    ( 
     AccountID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_3 
    ADD CONSTRAINT Relation_3_BillingAccount_FK FOREIGN KEY 
    ( 
     BillingAccount_BillingAccountID
    ) 
    REFERENCES BillingAccount 
    ( 
     BillingAccountID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_30 
    ADD CONSTRAINT Relation_30_Associate_FK FOREIGN KEY 
    ( 
     Associate_AssociateID
    ) 
    REFERENCES Associate 
    ( 
     AssociateID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_30 
    ADD CONSTRAINT Relation_30_OrgUnit_FK FOREIGN KEY 
    ( 
     OrgUnit_OrgUnitID
    ) 
    REFERENCES OrgUnit 
    ( 
     OrgUnitID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_31 
    ADD CONSTRAINT Relation_31_Associate_FK FOREIGN KEY 
    ( 
     Associate_AssociateID
    ) 
    REFERENCES Associate 
    ( 
     AssociateID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_31 
    ADD CONSTRAINT Relation_31_Contest_FK FOREIGN KEY 
    ( 
     Contest_ContestID
    ) 
    REFERENCES Contest 
    ( 
     ContestID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_32 
    ADD CONSTRAINT Relation_32_Associate_FK FOREIGN KEY 
    ( 
     Associate_AssociateID
    ) 
    REFERENCES Associate 
    ( 
     AssociateID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_32 
    ADD CONSTRAINT Relation_32_Customer_FK FOREIGN KEY 
    ( 
     Customer_CustomerID
    ) 
    REFERENCES Customer 
    ( 
     CustomerID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_39 
    ADD CONSTRAINT Relation_39_Account_FK FOREIGN KEY 
    ( 
     Account_AccountID
    ) 
    REFERENCES Account 
    ( 
     AccountID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_39 
    ADD CONSTRAINT Relation_39_Account_FKv1 FOREIGN KEY 
    ( 
     Account_AccountID1
    ) 
    REFERENCES Account 
    ( 
     AccountID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_5 
    ADD CONSTRAINT Relation_5_Account_FK FOREIGN KEY 
    ( 
     Account_AccountID
    ) 
    REFERENCES Account 
    ( 
     AccountID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE Relation_5 
    ADD CONSTRAINT Relation_5_Administrator_FK FOREIGN KEY 
    ( 
     Administrator_AdminID
    ) 
    REFERENCES Administrator 
    ( 
     AdminID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

ALTER TABLE WritingNumber 
    ADD CONSTRAINT WritingNumber_Associate_FK FOREIGN KEY 
    ( 
     Associate_AssociateID
    ) 
    REFERENCES Associate 
    ( 
     AssociateID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            29
-- CREATE INDEX                             0
-- ALTER TABLE                             81
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                 326
-- WARNINGS                                 0
